---
kind: pipeline
name: build

steps:
  - name: build and push image
    image: plugins/docker
    settings:
      registry: cr.37-27-0-62.sslip.io
      repo: cr.37-27-0-62.sslip.io/lbogdan/example-app
      tags:
      - latest
      - ${DRONE_TAG}
      username: lbogdan
      password:
        from_secret: harbor-password
      build_args:
        - VERSION=${DRONE_TAG}

trigger:
  ref:
  - refs/tags/v*
---
kind: signature
hmac: 0ae779c7a9604a71a554e90341e7891a40e6182ad31e2b68f2ea0b878532fe0d

...
