---
kind: pipeline
name: branch

steps:
  - name: build and push image
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/lbogdan/example-app
      tags:
      - latest
      - ${DRONE_TAG}
      username: lbogdan
      password:
        from_secret: ghcr-password

trigger:
  ref:
  - refs/tags/v*
---
kind: signature
hmac: f5c9b7774e68578b71500449e39a43f6dd896a402e6a89f30a6a941472778f1f

...
