---
kind: pipeline
name: build

steps:
  - name: build and push image
    image: plugins/docker
    settings:
      registry: cr.37-27-0-62.sslip.io
      repo: cr.37-27-0-62.sslip.io/lbogdan/example-app
      tags:
      - latest
      - ${DRONE_TAG}
      username: lbogdan
      password:
        from_secret: harbor-password

trigger:
  ref:
  - refs/tags/v*
---
kind: signature
hmac: 908aca4e5d629da35829cb2cfc525144099a151fc2a5c39aa26c40d7fddc2abc

...
