{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- if .Values.ingress.tls }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ required "ingress.host is not set" .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "helm.fullname" . }}
            port:
              name: http
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: "{{ .Values.ingress.host }}-tls"
  {{- end }}
{{- end -}}
