apiVersion: v1
kind: Secret
metadata:
  name: example-app-postgresql
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
type: Opaque
