apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- /*  # type: {{ .Values.service.type }}
  # type: ClusterIP # default */}}
