apiVersion: v2
name: example-app
description: A Helm chart for the example-app for the Advanced Kubernetes Workshop
type: application
version: v0.0.1
appVersion: v0.0.20

dependencies:
- name: postgresql
  version: 13.1.5
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
