environment: development

config:
  dbType: sqlite
  sqliteDbPath: /data/example-app.sqlite

replicas: 1

image:
  registry: cr.37-27-0-62.sslip.io
  repository: lbogdan/example-app
  tag: v0.0.20

ingress:
  enabled: false
  className: nginx
  tls: false

security:
  enabled: false
  network: false

postgresql:
  enabled: false
  primary:
    persistence:
      size: 1Gi
  auth:
    enablePostgresUser: false
    username: example-app

    # this is not used, it's only set to fix a helm-diff issue:
    # diff is breaking for specific checks performed by bitnami/common -
    # https://github.com/databus23/helm-diff/issues/460
    password: dummy

    database: example-app
    existingSecret: example-app-postgresql
    secretKeys:
      userPasswordKey: password

secrets:
  postgresPassword: ajRvm5BQpAUQqWFB

resources:
  requests:
    cpu: 500m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 256Mi

autoscale:
  enabled: false

externalPostgresql:
  enabled: false
  host: ""
  username: ""
  database: ""

probes:
  readiness:
    enabled: true
    httpGet:
      path: /healthz
      port: 3000
  liveness:
    enabled: false
    httpGet:
      path: /livez
      port: 3000
