environment: development

config:
  # number of bcrypt rounds used in /hash
  rounds: 10
  # database type used for /counter; one of sqlite, postgresql
  dbType: sqlite
  sqliteDbPath: /data/example-app.sqlite

replicas: 1

image:
  registry: ghcr.io
  repository: lbogdan/example-app
  tag: v0.0.20

ingress:
  enabled: false
  host: ""
  className: nginx
  tls: false

security:
  # add container settings to pass the restricted Pod Security Standard
  enabled: false
  # create network policy that only allows connections to the database from the app
  network: false

postgresql:
  enabled: false
  primary:
    persistence:
      size: 1Gi
  auth:
    enablePostgresUser: false
    username: example-app
    # this is not used, it's only set to fix a helm-diff issue:
    # diff is breaking for specific checks performed by bitnami/common -
    # https://github.com/databus23/helm-diff/issues/460
    password: dummy
    database: example-app
    existingSecret: example-app-postgresql
    secretKeys:
      userPasswordKey: password

secrets:
  postgresPassword: ajRvm5BQpAUQqWFB

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 256Mi

autoscale:
  enabled: false
  maxReplicas: 4
  # in procents, relative to resource.requests.cpu (not limits)
  # e.g. when requests.cpu is 250m, average utilization is 250m x 200% = 500m
  averageUtilization: 200
  scaleDown:
    stabilizationWindowSeconds: 60

externalPostgresql:
  enabled: false
  host: ""
  username: ""
  database: ""

probes:
  readiness:
    enabled: true
    httpGet:
      path: /healthz
      port: http
  liveness:
    enabled: false
    httpGet:
      path: /livez
      port: http
