name: Build

on:
  push:
    tags: v[0-9]*

jobs:
  build:
    runs-on: github-actions
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      -
        name: Show environment
        run: env
