name: Build

on:
  push:
    tags: v[0-9]*

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      # -
      #   name: Show environment
      #   run: env
      -
        name: Build and push image
        run: ./scripts/build.sh --push
