name: Build

on:
  push:
    tags: v[0-9]*

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v4
      # -
      #   name: Show environment
      #   run: env
      -
        name: Login to GitHub container registry
        run: echo $GH_TOKEN | docker login ghcr.io -u lbogdan --password-stdin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push image
        run: ./scripts/build.sh --push
